### ISSUE TITLE
DirectorUrl Ansible variable?

### ISSUE THREAD

**Issue by riahc3** [ryancbutler/Citrix-VAD-LAB#4]
Hello

Installing Director, I get that the DirectorUrl variable does not exist....

Using Visual Studio Code, I tried to search the entire project for DirectorUrl but it could not find it (except in the playbook)

Is this missing somewhere? Also, I imagine it is for getting the full URL to the Director right? I ask this so maybe I could fix it myself using Powershell.

Thank you

**Comment by ryancbutler** [comment]
It uses the computer name found in the https://github.com/ryancbutler/Citrix-VAD-LAB/blob/master/ansible/roles/director/files/configuredefault.ps1

```$Text = @"
<script type="text/javascript">
<!--
window.location="http://$env:computername.$env:userdnsdomain/Director";
// -->
</script>
"@```

**Comment by SpodoY** [comment]
I encountered the same problem as riahc3, unfortunately I still don’t get what you mean with your response. Since it’s declared with {{ }} ansible tries to look for it in the vars.yml file, where it’s not included, hence the error.

Am I missing something or how am I supposed to fix this error ?

Thank you in advance!

**Comment by ryancbutler** [comment]
Ahh I see. Been a bit.

I looks like the DirectorUrl is never used. So it can be removed from https://github.com/ryancbutler/Citrix-VAD-LAB/blob/309228ae5a24d37dcd8976b97567f13ffc980bbe/ansible/roles/director/tasks/main.yml#L68

**Comment by ryancbutler** [comment]
I have removed this from the branch as well
